[project]
name = "casper"
version = "0.0.1"
authors = [{ name = "Andrea Cuteri", email = "andrea.cuteri@unical.it" }]
description = "A solver for 2-ASP(Q)"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clingo>=5.7.1",
]

[project.scripts]
casper = "casper.app:entrypoint"

[tool.setuptools.packages.find]
where = ["."]

